# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Titan' do
    # Comment this line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Titan
    
    pod 'OAuthSwift', '~> 0.5.0'
    pod 'UIScrollView-InfiniteScroll'
    pod 'AFNetworking', '~> 2.5'
    pod 'BDBOAuth1Manager'
    
    target 'TitanTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'TitanUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
